### ISSUE TITLE
FRQ - Textumbruch in der Beschreibung  Projektaufgaben

### ISSUE THREAD

**Issue by henningeilers** [PMD3VSolution/NFA_DOC#104]
![grafik](https://user-images.githubusercontent.com/89243951/141097937-04735f78-e470-479f-8173-46560ea267c8.png)

Hallo Ranjid, 

nach dem letzten frohlockenden Gesprächen, hoffe ich zutiefst, dass du mir nochmals helfen kannst.
Es wäre tatsächlich sehr famos, wenn du in der Beschreibung einen Textumbruch einbauen könnest oder mindestens die Größe ändern.

Viele Grüße

**Comment by PMD3VSolution** [comment]
Du mit deiner Bongoauflösung ;) kauf dir lieber mal ne Brille ** Lach **
Ok ich kümmere mich darum =)

**Comment by PMD3VSolution** [comment]
Umgesetzt und ab sofort nutzbar
