### ISSUE TITLE
Sortierung Übersicht auch bei AV

### ISSUE THREAD

**Issue by henningeilers** [PMD3VSolution/NFA_DOC#113]
Hi Peter,
kannst du in den Übersichten die Sortierung auch bei AV einrichten? ich hätte gerne meine Projekte / Kunden untereinander.

Lass uns drüber sprechen :-)

**Comment by PMD3VSolution** [comment]
![grafik](https://user-images.githubusercontent.com/39301026/146686753-77ec3e17-6889-4535-8677-8df44db8a7ff.png)

**Comment by PMD3VSolution** [comment]
![grafik](https://user-images.githubusercontent.com/39301026/146686819-956e3035-f63f-40a8-8b7d-cf0d09b39b3d.png)

**Comment by PMD3VSolution** [comment]
![grafik](https://user-images.githubusercontent.com/39301026/146686854-6257b609-9108-4b4f-9876-afe710a2a1be.png)
