### ISSUE TITLE
FRQ - Langtext Einträge bearbeiten / löschen

### ISSUE THREAD

**Issue by henningeilers** [PMD3VSolution/NFA_DOC#116]
Hi Peter,
Ronny ist aufgefallen, dass man in den Projektaufgaben die Langtexteinträge nicht ändern bzw. löschen kann. Siehe BDK Miraki Projekt.

**Comment by PMD3VSolution** [comment]
![grafik](https://user-images.githubusercontent.com/39301026/155875002-6af89e43-dfe4-4d21-9df1-4caeb1b19dbb.png)

**Comment by PMD3VSolution** [comment]
![grafik](https://user-images.githubusercontent.com/39301026/155875008-a55fe2bb-b58c-4c49-a8d0-63fd8f3b34f0.png)

**Comment by PMD3VSolution** [comment]
Umgesetzt
