### ISSUE TITLE
Projekte auf Dashboard hinterlegen

### ISSUE THREAD

**Issue by carlosparman** [PMD3VSolution/NFA_DOC#132]
Aktuell lassen sich auf dem Dashboard nur Projekte mit Konflikten anzeigen.  
Es wäre praktisch wenn man sich die eigenen Projekte oder Projekte nach Wahl auf dem Dashboard anzeigen lassen könnte.

**Comment by PMD3VSolution** [comment]
Welcher Mehrwert soll dadurch erziehlt werden ?

**Comment by PMD3VSolution** [comment]
![grafik](https://user-images.githubusercontent.com/39301026/186548347-14388bcc-b8fd-4f7e-9e32-17c8a5e211ad.png)

technisch über die rechte Navigationsleiste gelöst
