### ISSUE TITLE
FRQ - Freitextfeld bei Herstellerverträge

### ISSUE THREAD

**Issue by henningeilers** [PMD3VSolution/NFA_DOC#147]
Hallo Peter,

wir hätten gerne noch ein Freitextfeld bei den Herstellerverträgen, sodass wir noch zusätzliche Informationen hinterlegen können.

Danke & Gruß

Henning

Prio 3

**Comment by PMD3VSolution** [comment]
![grafik](https://user-images.githubusercontent.com/39301026/169383962-84ba48b9-ae81-460b-90c7-fa56ef28b12b.png)
Anforderung wurde wie gewünscht umgesetzt
