### ISSUE TITLE
Servicezeiten hinzufügen

### ISSUE THREAD

**Issue by henningeilers** [PMD3VSolution/NFA_DOC#54]
Bitte Servicezeiten bei IM und Changemanagement hinzufügen. Danke.

**Comment by PMD3VSolution** [comment]
Anforderung wurde wie gewünscht umgesetzt und getestet:
![grafik](https://user-images.githubusercontent.com/39301026/130674226-2592844b-0734-4ceb-9718-959e7901b291.png)

![grafik](https://user-images.githubusercontent.com/39301026/130674292-01ec6580-2c59-4212-a7f0-555c0a6a2e6f.png)

**Comment by PMD3VSolution** [comment]
Ticket geschlossen
