### ISSUE TITLE
Hersteller hinzufügen

### ISSUE THREAD

**Issue by henningeilers** [PMD3VSolution/NFA_DOC#57]
Bei Herstellern sollten wir auch einen Hinzufügen Knopf haben. Aktuell fehlt mir z.B. TLAN bei Apologistics

**Comment by PMD3VSolution** [comment]
![grafik](https://user-images.githubusercontent.com/39301026/130848916-d825bc78-0e08-407e-b3df-a4be06811170.png)
 Neue Hersteller können über das Menü hinzugefügt werden.

shortcut wurde erstellt:
![grafik](https://user-images.githubusercontent.com/39301026/130848977-d6e8b5a9-c65e-463e-b3ac-fd83e697aa40.png)
