### ISSUE TITLE
Wiederherstellungs- / Ausführungszeit 

### ISSUE THREAD

**Issue by henningeilers** [PMD3VSolution/NFA_DOC#60]
Bei Incident- und Changemanagement muss es zusätzlich zur Reaktionszeit auch die Wiederherstellungs- / Ausführungszeit geben

**Comment by PMD3VSolution** [comment]
![grafik](https://user-images.githubusercontent.com/39301026/131078937-f2fe74be-92bf-431e-b510-49c7a0016364.png)
