### ISSUE TITLE
Eventmanagement

### ISSUE THREAD

**Issue by henningeilers** [PMD3VSolution/NFA_DOC#61]
Zu Incident und Changemanagement benötigen wir noch das Eventmanagement mit Reaktions- und Wiederherstellungszeit.

**Comment by PMD3VSolution** [comment]
-> Servicezeit
-> reaktionszeit

**Comment by PMD3VSolution** [comment]
Wiederherstellungszeit

**Comment by PMD3VSolution** [comment]
![grafik](https://user-images.githubusercontent.com/39301026/131076133-c627d910-e092-476d-9433-6760efa0f79d.png)
Anforderung wurde umgesetzt
