### ISSUE TITLE
Service auf Abruf

### ISSUE THREAD

**Issue by henningeilers** [PMD3VSolution/NFA_DOC#62]
Als Vertragsinhalt muss Service auf Abruf mit aufgenommen werden

**Comment by PMD3VSolution** [comment]
-> servicezeit
->reaktionszeit
-> ausführungszeit

**Comment by PMD3VSolution** [comment]
![grafik](https://user-images.githubusercontent.com/39301026/131076159-6e9792fc-b2af-4dcd-9f28-85af5e5a84a2.png)
Anforderung wurde umgesetzt
