### ISSUE TITLE
Report Widget Projekte und Konflikte

### ISSUE THREAD

**Issue by henningeilers** [PMD3VSolution/NFA_DOC#96]
Ich hätte gerne noch das Unternehmen mit in dem Report-Widget.

Dazu einen 9er Chicken Mc Nugget BBQ , einen Cheeseburger, eine kleine Pommes und ein mittleres Wasser.

Danke

**Comment by PMD3VSolution** [comment]
![grafik](https://user-images.githubusercontent.com/39301026/138534394-a37c4396-b1bc-473e-ab8d-608f82236154.png)

Die Anforderung wurde wie besprochen umgesetzt.
